// ─── Sample Listings ────────────────────────────────────────────────────────

const makePhotos = (seed, count = 35) =>
  Array.from({ length: count }, (_, i) =>
    `https://picsum.photos/seed/${seed}-${i}/900/600`
  );

export const listings = [
  {
    id: 1,
    address: "4217 Magnolia Ridge Drive",
    city: "Brentwood",
    state: "TN",
    zip: "37027",
    price: 1_195_000,
    beds: 5,
    baths: 4.5,
    sqft: 4_680,
    lotSize: "0.62 acres",
    garage: 3,
    stories: 2,
    yearBuilt: 2019,
    mlsId: "MLS2024001",
    status: "Active",
    propertyType: "Single Family",
    architecturalStyle: "Modern Farmhouse",
    hoaDues: 245,
    propertyTaxPct: 1.15,
    loanTerm: 30,
    downPaymentPct: 20,
    schools: {
      high: "Ravenwood High School",
      middle: "Woodland Middle",
      elementary: "Crockett Elementary",
    },
    exterior: {
      stories: 2,
      garageSpaces: 3,
      waterSource: "Public / Municipal",
      lotFeatures: "Corner Lot, Professionally Landscaped, Level",
      parking: "Attached Garage, Extended Driveway",
      heatType: "Gas Forced Air, Zoned",
      ac: "Central Air, Dual Zone",
      sewer: "Public Sewer",
      substructure: "Poured Concrete",
    },
    interior: {
      totalRooms: 13,
      bedrooms: 5,
      fullBaths: 4,
      halfBaths: 1,
      laundry: "Main Level Utility Room",
      flooring: "White Oak Hardwood, Porcelain Tile",
      fireplace: "Gas Log — Living Room & Primary Suite",
      appliances: "Wolf Range, Sub-Zero Refrigerator, Bosch Dishwasher",
    },
    features: [
      "Waterfall Kitchen Island",
      "10-Ft Coffered Ceilings",
      "Mudroom with Custom Built-ins",
      "Covered Outdoor Living",
      "Wine Cellar",
      "Bonus Room",
      "Smart Home System",
    ],
    description: `Welcome to 4217 Magnolia Ridge Drive — a masterfully crafted Modern Farmhouse set on nearly two-thirds of an acre in one of Brentwood's most sought-after communities.\n\nThis 4,680 sq ft residence was completed in 2019 and blends timeless architectural detail with an intentional, open floor plan. The main level offers a chef's kitchen anchored by an oversized waterfall island, Wolf appliances, and custom cabinetry that flows seamlessly into the great room with 10-foot coffered ceilings and a gas fireplace.\n\nThe primary suite occupies its own wing, featuring a spa bath with heated floors, soaking tub, and direct access to a private covered terrace. Four additional bedrooms offer generous closet space and en-suite or shared bath configurations. A fully finished bonus room above the garage is ideal for a media room, playroom, or home office.\n\nOutdoors, the covered patio with outdoor kitchen is ready for year-round entertaining. Three-car garage, extended driveway, and whole-home smart system complete this exceptional offering.`,
    photos: makePhotos("magnolia"),
  },
  {
    id: 2,
    address: "811 Greystone Cove Lane",
    city: "Nashville",
    state: "TN",
    zip: "37215",
    price: 785_000,
    beds: 4,
    baths: 3,
    sqft: 3_120,
    lotSize: "0.33 acres",
    garage: 2,
    stories: 2,
    yearBuilt: 2015,
    mlsId: "MLS2024002",
    status: "Active",
    propertyType: "Single Family",
    architecturalStyle: "Traditional Craftsman",
    hoaDues: 0,
    propertyTaxPct: 1.22,
    loanTerm: 30,
    downPaymentPct: 20,
    schools: {
      high: "Hillsboro High School",
      middle: "West End Middle School",
      elementary: "Eakin Elementary",
    },
    exterior: {
      stories: 2,
      garageSpaces: 2,
      waterSource: "Metro Water Services",
      lotFeatures: "Wooded Rear Lot, Mature Trees, Cul-de-Sac",
      parking: "Attached 2-Car Garage, Side-Entry",
      heatType: "Gas Forced Air",
      ac: "Central Air",
      sewer: "Metro Sewer",
      substructure: "Crawl Space with Encapsulation",
    },
    interior: {
      totalRooms: 10,
      bedrooms: 4,
      fullBaths: 3,
      halfBaths: 0,
      laundry: "Second Floor",
      flooring: "Hardwood, Carpet in Bedrooms",
      fireplace: "Wood Burning — Family Room",
      appliances: "Stainless Steel Package — KitchenAid",
    },
    features: [
      "Kitchen Island with Bar Seating",
      "Vaulted Ceilings in Primary",
      "Walk-in Pantry",
      "Screened Porch",
      "Fenced Backyard",
    ],
    description: `Nestled on a quiet cul-de-sac lot in Green Hills, 811 Greystone Cove Lane offers a rare combination of location, quality construction, and practical layout in one of Nashville's most desirable zip codes.\n\nBuilt in 2015, this Traditional Craftsman is move-in ready with fresh interior paint, hardwood floors throughout the main level, and an updated kitchen featuring a large island, walk-in pantry, and stainless appliance suite. The open plan connects kitchen to family room anchored by a wood-burning fireplace with custom surround.\n\nUpstairs, four bedrooms including a primary suite with vaulted ceilings, spa-inspired bath, and dual walk-ins. Three full baths total. Second-floor laundry. Attached two-car garage.\n\nOutdoors enjoy a screened porch, fully fenced backyard, and mature trees providing exceptional privacy. Walkable to Hillsboro Village, top-rated schools, and major corridors.`,
    photos: makePhotos("greystone"),
  },
  {
    id: 3,
    address: "2095 Autumn Chase Court",
    city: "Franklin",
    state: "TN",
    zip: "37067",
    price: 565_000,
    beds: 3,
    baths: 2.5,
    sqft: 2_280,
    lotSize: "0.18 acres",
    garage: 2,
    stories: 2,
    yearBuilt: 2021,
    mlsId: "MLS2024003",
    status: "Pending",
    propertyType: "Single Family",
    architecturalStyle: "Contemporary",
    hoaDues: 180,
    propertyTaxPct: 0.98,
    loanTerm: 30,
    downPaymentPct: 10,
    schools: {
      high: "Franklin High School",
      middle: "Freedom Middle School",
      elementary: "Oak View Elementary",
    },
    exterior: {
      stories: 2,
      garageSpaces: 2,
      waterSource: "Public",
      lotFeatures: "Level, HOA Common Greenspace",
      parking: "Attached 2-Car Garage, Alley Load",
      heatType: "Electric Heat Pump",
      ac: "Heat Pump",
      sewer: "Public Sewer",
      substructure: "Slab",
    },
    interior: {
      totalRooms: 8,
      bedrooms: 3,
      fullBaths: 2,
      halfBaths: 1,
      laundry: "Second Floor Closet",
      flooring: "LVP Main Level, Carpet Upper",
      fireplace: "None",
      appliances: "Samsung Stainless Package",
    },
    features: [
      "Kitchen Island",
      "Open Concept Main Level",
      "Primary Suite Balcony",
      "Ring Smart Doorbell",
      "EV Charger Rough-In",
    ],
    description: `Built in 2021, 2095 Autumn Chase Court is a contemporary new-construction home in the highly sought-after Liberty Hills community in Franklin. Clean lines, designer finishes, and a smart open plan make this home feel larger than its 2,280 square feet.\n\nThe main level features LVP flooring throughout, a bright open kitchen with quartz counters, large island, and Samsung stainless appliances that flow directly into the dining and living spaces — ideal for everyday living and entertaining alike.\n\nUpstairs, three bedrooms including a primary suite with private balcony, walk-in closet, and luxe bath with dual vanity and oversized shower. Two additional bedrooms share a full hall bath, with laundry conveniently located between them.\n\nAlley-load two-car garage with EV charger rough-in, Ring security, and low-maintenance exterior round out this turnkey package. HOA covers community pool, greenspace, and common maintenance.`,
    photos: makePhotos("autumn"),
  },
];

// ─── Sample Articles ────────────────────────────────────────────────────────

export const articles = [
  {
    id: 1,
    category: "Market Update",
    title: "Nashville Metro Inventory Is Rising — Here's What It Means for Buyers",
    summary:
      "After two years of historically low inventory, the Middle Tennessee market is showing signs of balance. Days-on-market are ticking up slightly, and buyers are seeing slightly more negotiating room than at any point since 2020. I walk through what this shift really means for pricing, offer strategy, and timing.",
    date: "April 12, 2025",
    source: "Williamson County Association of REALTORS®",
    sourceUrl: "https://www.wcarealtors.com",
    readTime: "4 min read",
  },
  {
    id: 2,
    category: "Buyer's Guide",
    title: "The Pre-Approval vs. Pre-Qualification Difference — and Why It Matters in a Competitive Market",
    summary:
      "A pre-qualification letter and a full pre-approval are not the same thing, and in a multiple-offer situation, that difference can cost you a home. I break down exactly what each one signals to a seller, how to strengthen your offer before you ever find a property, and what questions to ask your lender.",
    date: "March 28, 2025",
    source: "Consumer Financial Protection Bureau",
    sourceUrl: "https://www.consumerfinance.gov",
    readTime: "5 min read",
  },
  {
    id: 3,
    category: "Research",
    title: "How School District Ratings Actually Impact Resale Value — The Data May Surprise You",
    summary:
      "Buyers consistently rank school quality as a top factor, but the correlation between rating and price appreciation is more nuanced than the headline number suggests. Using recent sales data across Williamson and Davidson counties, I examine which school feeder patterns are translating into stronger long-term value.",
    date: "March 10, 2025",
    source: "National Association of REALTORS® Research",
    sourceUrl: "https://www.nar.realtor/research-and-statistics",
    readTime: "6 min read",
  },
  {
    id: 4,
    category: "Seller's Guide",
    title: "Five Things That Killed My Sellers' Weekend — and How We Fixed It",
    summary:
      "The first weekend on market is everything. I share five common presentation and pricing mistakes I've seen kill momentum in the opening days — from photography missteps to misreading the comp pool — and exactly what we do to set listings up for strong, multiple-offer launches.",
    date: "February 19, 2025",
    source: "National Association of REALTORS® Profile of Home Buyers and Sellers",
    sourceUrl: "https://www.nar.realtor",
    readTime: "4 min read",
  },
];

// ─── Agent Info ─────────────────────────────────────────────────────────────

export const agent = {
  name: "[Agent Name]",
  title: "REALTOR® | Buyer & Seller Specialist",
  realtorNumber: "TN-RE-XXXXXXXX",
  phone: "(615) 555-0192",
  email: "agent@premierproperties.com",
  instagram: "@premierproperties",
  facebook: "PremierPropertiesTN",
  linkedin: "in/agentname",
  bio: `[Agent bio will go here — introduce yourself, your story, your connection to the Nashville/Middle Tennessee market, and what drives your work.]

This space is yours to be genuine. Talk about your background, what led you to real estate, the neighborhoods you know best, and the kind of experience you're committed to giving every client. Buyers and sellers want to work with a real person — this is where they meet you first.`,
  team: [
    {
      name: "[Team Member 1]",
      role: "Buyer's Specialist",
      bio: "Team member bio placeholder.",
    },
    {
      name: "[Team Member 2]",
      role: "Transaction Coordinator",
      bio: "Team member bio placeholder.",
    },
  ],
};
